import type { Metadata } from "next";
import { Lora } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { cn } from "@/lib/utils";

const lora = Lora({ subsets: ["latin"], variable: "--lora" });

export const metadata: Metadata = {
  title: {
    template: "Px | %s",
    default: "Px Picture",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={cn(lora.variable, "font-Lora antialiased")}>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
